/*
ExecutionTrace

Represents the execution trace generated by the device.
The trace is a sequence of API identifiers.
*/

public class ExecutionTrace {

    private int[] apiSequence;

    public ExecutionTrace(int[] sequence) {

        this.apiSequence = sequence;

    }

    public int[] getSequence() {

        return apiSequence;

    }

    public int length() {

        return apiSequence.length;

    }

}