public class TestVerifier {

    public static void main(String[] args) {

        /*
        Load workflow graph generated by the extractor
        */

        WorkflowGraph graph = WorkflowLoader.loadGraph("../extractor/workflow_graph.json");

        int[] sequence = {1,2,3,4};

        ExecutionTrace trace = new ExecutionTrace(sequence);

        Verifier verifier = new Verifier(graph);

        boolean result = verifier.verify(trace);

        if(result) {

            System.out.println("TRACE VALID");

        } else {

            System.out.println("TRACE INVALID");

        }

    }

}