import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;
import org.json.simple.*;
import org.json.simple.parser.JSONParser;

/*
WorkflowLoader

This class loads a workflow graph from a JSON file
generated by the Python extractor.

The JSON format is:

{
  "edges":[
    [1,2],
    [2,3],
    [3,4]
  ]
}

Each edge represents a valid transition
between two API calls.
*/

public class WorkflowLoader {

    public static WorkflowGraph loadGraph(String filename) {

        WorkflowGraph graph = new WorkflowGraph(16);

        JSONParser parser = new JSONParser();

        try {

            Object obj = parser.parse(new FileReader(filename));

            JSONObject jsonObject = (JSONObject) obj;

            JSONArray edges = (JSONArray) jsonObject.get("edges");

            for(Object edge : edges) {

                JSONArray pair = (JSONArray) edge;

                int from = ((Long) pair.get(0)).intValue();
                int to = ((Long) pair.get(1)).intValue();

                graph.addEdge(from,to);

            }

        } catch(Exception e) {

            e.printStackTrace();

        }

        return graph;

    }

}