#ifndef VERIFIER_H
#define VERIFIER_H

#include <stdint.h>

/*
=====================================================================
VERIFIER MODULE
=====================================================================

This module implements the workflow execution verifier.

The verifier checks whether an execution trace generated by the
device is compatible with the workflow graph extracted from the
original program.

Formally the verifier checks if:

    execution_trace ∈ L(G)

Where:

    G  = workflow graph
    L(G) = language of valid API sequences allowed by the graph

If the trace is compatible with the graph:
    → execution is accepted

If the trace is not compatible:
    → execution may have been tampered with

=====================================================================
*/


/*
Maximum number of API calls that can be stored inside a trace.
This defines the maximum execution trace length supported by
the verifier.
*/

#define MAX_TRACE 1024


/*
Maximum number of different APIs supported by the system.

Each API is identified by a numeric identifier.
The workflow graph is defined over these identifiers.
*/

#define MAX_API   16


/*
=====================================================================
Execution Trace Structure
=====================================================================

This structure represents the sequence of API calls executed
by the device.

Example:

    INIT
    ASSIGN
    ADD
    DIV

Is represented as:

    [1,2,3,4]

Each value corresponds to an API identifier.
*/

typedef struct
{
    /*
    Ordered sequence of API identifiers.
    */
    uint32_t api_sequence[MAX_TRACE];

    /*
    Length of the trace.
    */
    uint32_t length;

} execution_trace;


/*
=====================================================================
verifier_init()

Initializes the workflow graph.

Internally the graph is represented as an adjacency matrix.
All transitions are initially set to invalid.
*/

void verifier_init();


/*
=====================================================================
verifier_add_edge()

Adds a valid transition to the workflow graph.

Example:

    verifier_add_edge(API_INIT, API_ASSIGN)

Means that ASSIGN can legally follow INIT in the workflow.
*/

void verifier_add_edge(uint32_t from, uint32_t to);


/*
=====================================================================
verifier_check_trace()

Checks whether the given execution trace is compatible with
the workflow graph.

Algorithm:

For each consecutive pair of API calls:

    api[i] → api[i+1]

If the transition does not exist in the graph:
    → TRACE INVALID

If all transitions exist:
    → TRACE VALID
*/

int verifier_check_trace(execution_trace *trace);


#endif